# This Dockerfile will be builded on DockerHub automated build configuration to create:
# - lorenzocalamandrei/angular-container:*.*.*-dev
# where *.*.* is the version of this Dockerfile
# The version will be taken from the tag by git.

# This Dockerfile extends:
# - lorenzocalamandrei/angular-container:*.*.*-base
ARG BASE_IMAGE=lorenzocalamandrei/laravel-php:1.4-php-7.4.2-base
FROM ${BASE_IMAGE}

LABEL mantainer="Lorenzo Calamandrei <nexcal.dev@gmail.com>"

USER root

# composer
RUN apt-get install curl > /dev/null && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

USER 1000
